int wait_for_wsupp_event(char *ifname, int sock, 
        int expiry_time,
        char *event,
        int ev_len);
int32_t                   
acfg_open_ev_sock (struct wsupp_ev_handle *wsupp_h);

#define WSUPP_AP_STA_CONNECTED "AP-STA-CONNECTED"
#define WSUPP_AP_STA_DISCONNECTED "AP-STA-DISCONNECTED"
#define WSUPP_CTRL_EVENT_CONNECTED "CTRL-EVENT-CONNECTED"
#define WSUPP_CTRL_EVENT_DISCONNECTED "CTRL-EVENT-DISCONNECTED"
#define WSUPP_CTRL_EVENT_ASSOC_REJECT "CTRL-EVENT-ASSOC-REJECT"
#define WSUPP_CTRL_EVENT_EAP_SUCCESS "CTRL-EVENT-EAP-SUCCESS"
#define WSUPP_CTRL_EVENT_EAP_FAILURE "CTRL-EVENT-EAP-FAILURE"
#define WSUPP_CTRL_EVENT_WPS_NEW_AP_SETTINGS "WPS-NEW-AP-SETTINGS"
#define WSUPP_CTRL_EVENT_WPS_REG_SUCCESS "WPS-REG-SUCCESS"
#define WSUPP_CTRL_EVENT_WPS_SUCCESS "WPS-SUCCESS"
#define WSUPP_CTRL_EVENT_WPS_ENROLLEE_SEEN "WPS-ENROLLEE-SEEN"
#define WSUPP_CTRL_EVENT_DPP_CONF_RECEIVED "DPP-CONF-RECEIVED"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_AKM "DPP-CONFOBJ-AKM"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_SSID "DPP-CONFOBJ-SSID"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_PASS "DPP-CONFOBJ-PASS"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_CONNECTOR "DPP-CONNECTOR"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_CSIGN "DPP-C-SIGN-KEY"
#define WSUPP_CTRL_EVENT_DPP_CONFOBJ_NETACCESSKEY "DPP-NET-ACCESS-KEY"

#define ACFG_APP_EVENT_INTERFACE_MOD "ACFG-EVENT-INTERFACE-ADD-DEL"
